[package]
name = "hlua51"
version = "0.4.1"
authors = [ "pierre.krieger1708@gmail.com" ]
description = "Zero-cost high-level wrapper for Lua"
keywords = ["lua"]
repository = "https://github.com/tomaka/hlua"
documentation = "http://docs.rs/hlua"
license = "MIT"

[dependencies]
libc = "0.2"
lua51-sys = { version = "0.1.1", path = "../lua51-sys" }
